export const cities = [
  { label: "İstanbul", value: "Istanbul" },
  { label: "Ankara", value: "Ankara" },
  { label: "İzmir", value: "Izmir" },
  { label: "Amasya", value: "Amasya" },
  { label: "Bursa", value: "Burdur" },
  { label: "Yalova", value: "Yalova" },
  { label: "Bolu", value: "Bolu" },
  { label: "Manisa", value: "Manisa" },
  { label: "Antalya", value: "Antalya" },
  { label: "Adana", value: "Adana" },
  { label: "Trabzon", value: "Trabzon" },
  { label: "Rize", value: "Rize" },
  { label: "Ordu", value: "Ordu" },
  { label: "Edirne", value: "Edirne" },
];
export const BASE_URL = `https://quince.mervfar.codes`;

// export const cities = [
//   { value: "İstanbul" },
//   { value: "Ankara" },
//   { value: "İzmir" },
//   { value: "Amasya" },
//   { value: "Bursa" },
//   { value: "Kocaeli" },
//   { value: "Yalova" },
//   { value: "Bolu" },
//   { value: "Manisa" },
//   { value: "Antalya" },
//   { value: "Adana" },
// ];
// export const carsDetails = [
//   {
//     brand: "Ford",
//     model: "Fiesta",
//     engine: "1.0 Ecoboost",
//     fuel: "Benzin",
//     gear: "PowerShift",
//     office: "AVIS Maslak",
//     deposit: "500",
//     dailyPrice: "98.50",
//     image: "https://source.unsplash.com/400x200/?car",
//   },
//   {
//     brand: "Ford",
//     model: "Focus",
//     engine: "1.0 Ecoboost",
//     fuel: "Benzin",
//     gear: "PowerShift",
//     office: "Budget Ataşehir",
//     deposit: "700",
//     dailyPrice: "139.50",
//     image: "https://source.unsplash.com/400x201/?car",
//   },
//   {
//     brand: "Honda",
//     model: "Civic",
//     engine: "1.6 CVT",
//     fuel: "Dizel",
//     gear: "Manuel",
//     office: "Enterprise Ayazağa",
//     deposit: "1000",
//     dailyPrice: "150",
//     image: "https://source.unsplash.com/401x200/?car",
//   },
//   {
//     brand: "Renault",
//     model: "Clio",
//     engine: "0.9",
//     fuel: "Benzin",
//     gear: "Manuel",
//     office: "AVIS Fikirtepe",
//     deposit: "300",
//     dailyPrice: "80",
//     image: "https://source.unsplash.com/402x200/?car",
//   },
// ];
