name: CI / CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    
    - name: Build with Maven
      run: mvn -Dmaven.test.skip=true clean install
    
    - name: Set Release Tag
      run: echo ::set-env name=RELEASE_VERSION::`date +%d%m%Y%H%M%S`
      
    - name: Set insecure-registries
      run: sudo sed -i '$s/}/,\n"insecure-registries":["http:\/\/docker.mervfar.codes:5005"]}/' /etc/docker/daemon.json
      
    - name: Restart the Docker
      run: sudo service docker restart
      
    - name: Read Docker deamon file 
      run: cat /etc/docker/daemon.json
      
    - name: Build from Dockerfile and Push to Docker
      uses: docker/build-push-action@v1
      with:
         repository: rentingApp
         registry: docker.mervfar.codes:5005
         #tags: ${{ env.RELEASE_VERSION }}
         tags: latest

  curl:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Send Deployment Request To Server
      uses: wei/curl@v1
      with:
        args: -X POST --data "secret=${{secrets.DEPLOYMENT_TOKEN}}" http://mervfar.codes:8080/deployment
